### ISSUE TITLE
Non idempotent tail() method

### ISSUE THREAD

**Issue by leafty** [dionyziz/stream.js#11]
The `tailPromise` function is evaluated each time we ask for the stream tail, so it can cause problems if it is not idempotent.
Example:
```js
var x = 0;
var f = function() { return new Stream(x++); }
var s = new Stream (1, f)

s.item(1)
// 0
s.item(1)
// 1
s.item(1)
// 2
```

When the tail is first evaluated, you should store it so that later calls do not recompute it.

**Comment by adamnew123456** [comment]
If you're still watching for this, pull request #26 (recently merged) makes this behavior the default, so that `Stream.tail` is only called once for a given `Stream`.

**Comment by dionyziz** [comment]
So I'm considering this resolved.
