### ISSUE TITLE
Coding style inconsistencies

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/stream.js#28]
Coding style seems inconsistent in the project due to various pull requests over the years. This may be a good chance to cleanup. @dotnetCarpenter since I see maybe that you prefer to avoid spaces directly after `(` and before `)`  and directly after `[` and before `]` perhaps we can make this change and try to make it consistent from now on and enforce coding style in PRs.

**Comment by dotnetCarpenter** [comment]
Yes. Should we be a bit more formal and add a linter? Perhaps [JSHint](https://github.com/jshint/jshint).

**Comment by dionyziz** [comment]
Sounds good.

**Comment by dotnetCarpenter** [comment]
We should close this when PR #36 is merged.
