### ISSUE TITLE
Using 'Infinity' for length value of non-finite streams

### ISSUE THREAD

**Issue by kflorence** [dionyziz/stream.js#4]
Streams without upper bounds can return the value [Infinity](https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Infinity) for their length. This could be used to detect non-finite streams in some of the other methods as well so as to better handle that situation.

**Comment by adrianmc** [comment]
I loved reading this thread. It reminds me of the first time I read GEB. Just curious though, is this feature being worked on still?

**Comment by dionyziz** [comment]
@adrianmc Not as far as I know of – please feel free to take it and work on it and submit a pull request as you see fit, I'll be very happy to see this get somewhere! :)

**Comment by GeorgeGkas** [comment]
This issue is inactive for years. We'll close it to for now and come back in the future -with a new issue- if there is still any interest.
